### ISSUE TITLE
Parameters using argv?

### ISSUE THREAD

**Issue by yellow** [crock/cli-checker#1]
I think parameters like site, wordlist, proxies and threads should be mentioned using sys.argv instead of a config file.

**Example**
`python3 OGCheckr.py -s twitter -w wordlist.txt -p proxies.txt -t 10`

Results should be appended to AVAILABLE_twitter.txt

**Comment by crock** [comment]
I did this in a previous release, but removed the feature during a major update. I planned to re-add them in a future release, but never did. If you are familiar with Python development, make a pull request and I’ll work with you to get it merged! 😉

**Comment by yellow** [comment]
I'm still learning. But I'll try to help!

I've also PMed you about another bot on the forums.

**Comment by yellow** [comment]
I've started liking the config.ini file more, it is more clearer while running the script as compared to using argv. Closing this now.
