### ISSUE TITLE
project over?

### ISSUE THREAD

**Issue by yellow** [crock/cli-checker#6]
Hello crock.
I can think of a few ways to speed up the program. Will you go through the pull request and accept if its good or should I just make a fork?

-yellow

**Comment by crock** [comment]
Definitely, when i said that OGC would have one final update, I meant by me exclusively. Anyone is welcome to make a well-tested PR that improves the checker in some way and I’ll merge it if everything checks out.

**Comment by yellow** [comment]
good to hear! Closing
